[package]
name = "praxis-tests-integration"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme = "../../README.md"
publish = false

[features]
cpex-policy-engine = ["praxis-filter/cpex-policy-engine"]
no-mac-cert-rotation-tests = [] # We use this to disable testing cert rotation on macOS
praxis-main = ["praxis-test-utils/praxis-main"]

[lints]
workspace = true

[dev-dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
jsonwebtoken = { workspace = true }
nix = { workspace = true }
praxis-core = { workspace = true }
praxis-filter = { workspace = true }
praxis-test-utils = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "io-util", "process"] }
tokio-tungstenite = { workspace = true }
